# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 799677a0c3384656b214c3ae8f170c6fd3bbd4ae9c3f60ae43191eb462a7b69f8127f62a94e370d6415a9b57b3745ae8bc627b9b6ce9634ca8d53d71509bfab0

test:
  secret_key_base: 46953e0c68254072614bd62df888b32dd56a24ddeba0da31dd31b3e09d17945d6deec6b712b8c1601b8347751f37869024fc4232eea87a86b207532720182d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
